version: "3.3"
services:
  fivefilters-full-text-rss:
    container_name: full-text-rss
    ports:
      - "50000:80"
    restart: always
    image: "heussd/fivefilters-full-text-rss:latest"
  linuxserver:
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - "80:80"
    volumes:
      - "./data:/config"  #bind host path of current working directory to /config on the guest
      - rss-data:/config #bind docker volume called rss-data to /config on guest
    restart: unless-stopped
    image: "lscr.io/linuxserver/freshrss:latest"
#volumes:   #only use if defining docker volume in line 18.
# rss-data:
#   name: rss-data
