global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

  dashboard:
    address: :8080

  heimdall:
    address: :8081
    
providers:
  docker:
    exposedByDefault: false
