version: "3.3"
services:
  Aggregator:
    container_name: "Aggregator"
    restart: "unless-stopped"
    image: "heussd/fivefilters-full-text-rss:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aggregator.rule=Host(`...`)"
      - "traefik.http.routers.aggregator.entrypoints=web,websecure"
      - "traefik.http.routers.aggregator.tls=true"
      - "traefik.http.routers.aggregator.tls.certresolver=production"

  FreshRss:
    container_name: "FreshRSS"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=America/New_York"
    volumes:
      - "rss-data:/var/www/FreshRSS/data"
    restart: "unless-stopped"
    image: "freshrss/freshrss:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feed.rule=Host(`...`)"
      - "traefik.http.routers.feed.entrypoints=web,websecure"
      - "traefik.http.routers.feed.tls=true"
      - "traefik.http.routers.feed.tls.certresolver=production"

volumes:
  rss-data:
    name: "rss-data"
    external: "true"
networks:
  default:
    name: Traefik
    external: true
