version: "3.3"
services:
  Traefik:
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-config:/etc/traefik"
      - "traefik-ssl-certs:/ssl-certs"
    restart: "unless-stopped"

  Aggregator:
    container_name: "Aggregator"
    restart: "always"
    image: "heussd/fivefilters-full-text-rss:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aggregator.rule=Host(`aggregator.docker`)"
      - "traefik.http.routers.aggregator.entrypoints=websecure"
      - "traefik.http.routers.aggregator.tls=true"

  FreshRss:
    container_name: "FreshRSS"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=America/New_York"
    volumes:
      - "rss-data:/var/www/FreshRSS/data"
    restart: "unless-stopped"
    image: "freshrss/freshrss:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feed.rule=Host(`feed.docker`)"
      - "traefik.http.routers.feed.entrypoints=websecure"
      - "traefik.http.routers.feed.tls=true"

volumes:
  rss-data:
    name: "rss-data"
    external: "true"  
  traefik-ssl-certs:
    name: "traefik-ssl-certs"
    external: "true"
