version: "3.3"
services:
  Nginx:
    container_name: "Nginx"
    restart: "unless-stopped"
    image: "nginx"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`...`)"
      - "traefik.http.routers.nginx.entrypoints=web,websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=production"
    volumes:
      - "./html:/usr/share/nginx/html"
networks:
  default:
    name: Traefik
    external: true
