---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:

title: "Homepage"
theme: "dark"
color: "slate"
showStats: "true"
background: 
  image: "https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80"
  blur: "sm"
  saturate: "50"
  brightness: "50"
  opacity: "50"

layout:
  Console:
    style: "row"
    columns: "2"

  Services:
    style: "row"
    columns: "2"
